# Generated by Django 5.1.5 on 2025-02-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habits",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Введите Вознаграждение ",
                        max_length=250,
                        null=True,
                        verbose_name="Вознаграждение ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
