# Generated by Django 5.1.5 on 2025-02-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habits",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "place",
                    models.CharField(help_text="Введите Место", max_length=250, verbose_name="Место выполнения"),
                ),
                ("time", models.TimeField(verbose_name="Время выполнения")),
                ("action", models.CharField(max_length=255, verbose_name="Действие")),
                (
                    "pleasant_habit_flag",
                    models.BooleanField(
                        help_text="Введите Признак", max_length=250, verbose_name="Признак приятной привычки"
                    ),
                ),
                ("frequency", models.PositiveIntegerField(default=1, verbose_name="Периодичность")),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Введите Вознаграждение ",
                        max_length=250,
                        null=True,
                        verbose_name="Вознаграждение ",
                    ),
                ),
                ("time_to_perform", models.PositiveIntegerField(verbose_name="Время на выполнение")),
                ("publicity_flag", models.BooleanField(default=False, verbose_name="Признак публичности")),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
