# Generated by Django 5.1.5 on 2025-02-15 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("habits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="habits",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="habits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель привычки",
            ),
        ),
        migrations.AddField(
            model_name="habits",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"pleasant_habit_flag": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="habits.habits",
                verbose_name="Связанная привычка",
            ),
        ),
    ]
